### ISSUE TITLE
cant even upload the log because spam of this same error is simply too big, it is impossible to change dimensions or end the game because of this error

### ISSUE THREAD

**Issue by Aabaddon** [Nuparu00/TinyInv#13]
[18:01:26] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundClientCommandPacket@3da5ad28, suppressing error
java.lang.NullPointerException: Cannot invoke "nuparu.tinyinv.capabilities.IExtendedPlayer.copy(nuparu.tinyinv.capabilities.IExtendedPlayer)" because "extendedPlayer" is null
	at nuparu.tinyinv.capabilities.CapabilityEventHandler.onPlayerClone(CapabilityEventHandler.java:34) ~[tinyinv-1.20.1-1.1.0.0.jar%23521!/:1.20.1-1.1.0.0]
	at nuparu.tinyinv.capabilities.__CapabilityEventHandler_onPlayerClone_Clone.invoke(.dynamic) ~[tinyinv-1.20.1-1.1.0.0.jar%23521!/:1.20.1-1.1.0.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:540) ~[forge-1.20.1-47.2.20-universal.jar%23547!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9015_(ServerPlayer.java:1159) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:442) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1510) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:24) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(ServerboundClientCommandPacket.java:6) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23542!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Aabaddon** [comment]
[18:06:30] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundClientCommandPacket@7fd3b20b, suppressing error
java.lang.NullPointerException: null

**Comment by Nuparu00** [comment]
Has been fixed in 1.20.1-1.1.0.1
